"""update long_url to add indexing

Revision ID: f63848c4be49
Revises: 933bdc11db53
Create Date: 2025-12-12 21:56:06.248855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63848c4be49'
down_revision = '933bdc11db53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('urls_long_url_key', 'urls', type_='unique')
    op.create_index(op.f('ix_urls_long_url'), 'urls', ['long_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urls_long_url'), table_name='urls')
    op.create_unique_constraint('urls_long_url_key', 'urls', ['long_url'])
    # ### end Alembic commands ###